### ISSUE TITLE
Block public access to S3 state buckets

### ISSUE THREAD

**Issue by jmcvetta** [boltops-tools/terraspace#161]
## Summary

Currently, when Terraspace creates an S3 bucket to hold state files, it does not configure the bucket to block all public access.  

![image](https://user-images.githubusercontent.com/55682/145431721-eea471bf-5cdf-4dbd-b52b-4456d220e5f1.png)

The state files are still protected, because they can only be read by owner.  Nevertheless definitively blocking all public access to the bucket is strongly suggested for defense in depth.

## Motivation

This feature improves Terraspace security.

## Guide-level explanation

When Terraspace automatically creates an S3 bucket for remote state, it ensures that bucket is protected against public access.

## Reference-level explanation

This proposal adds a Public Access Block to the S3 bucket configuration.

* [Terraform `aws_s3_bucket_public_access_block` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block)
* [CloudFormation `PublicAccessBlockConfiguration` documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html)
* ["Configuring block public access settings for your S3 buckets" AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/configuring-block-public-access-bucket.html)

## Drawbacks

There is no drawback.

## Unresolved Questions

No unresolved questions.

**Comment by jmcvetta** [comment]
@tongueroo If you can point me in the right direction, I will submit a PR to implement this feature request.  Where in the code does it create the S3 state bucket?

**Comment by jmcvetta** [comment]
Looks like the state bucket is created by the AWS plugin over in this repo: https://github.com/boltops-tools/terraspace_plugin_aws

**Comment by tongueroo** [comment]
Yup. You found it. 👍 Looked and it's actually 2 repos that would have to be updated.

* https://github.com/boltops-tools/terraspace_plugin_aws
* https://github.com/boltops-tools/s3-secure

Code trace:

terraspace_plugin_aws:

* Where the secure settings are applied https://github.com/boltops-tools/terraspace_plugin_aws/blob/master/lib/terraspace_plugin_aws/interfaces/backend/bucket.rb#L13
* The secure method calls another lib https://github.com/boltops-tools/terraspace_plugin_aws/blob/master/lib/terraspace_plugin_aws/interfaces/backend/bucket/secure.rb

That other lib is s3_secure:

* So would add class and method. Something like PublicAccess#block to https://github.com/boltops-tools/s3-secure/tree/master/lib/s3_secure
* Then the terraspace_plugin_aws would be able to call that new class and method.

It's a few steps. No sweat either way of course. 😄  Appreciate it if you get to it. Otherwise, hope to get to it in time. ⏱ Thanks!

**Comment by tongueroo** [comment]
Docs: https://terraspace.cloud/docs/plugins/aws/

**Comment by jmcvetta** [comment]
Awesome!
