### ISSUE TITLE
Terraspace all should halt on any error

### ISSUE THREAD

**Issue by johnlister** [boltops-tools/terraspace#298]
## Checklist

- [X ] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |      Win 10 WSL v2  |
| Terraform        |      1.3.6   |
| Terraspace       |      2.2.3   |
| Ruby             |      3.0.3p157   |

---

## Expected Behaviour

**terraspace all** should stop on any error at each level. Further processing needs to be halted if any stack results in an error.

## Current Behavior

**terraspace all** continues to process further levels in the tree. For a _terraspace up_ this is usually fairly safe as any dependencies will normally fail or at worst generate incorrect resources. However for _terraspace down_ this can be catestrophic, as the tree is parsed backwards, the stacks at the top of the tree (dependencies) are processed and destroyed. This forcibly breaks any dependencies in the lower stacks and prevents them being cleaned up or applied.

## Step-by-step reproduction instructions

For example if A depends on B and A fails to be destroyed on _terraspace down_ then B will be destroyed anyway. Any dependencies in A now return an error as the outputs from B no longer exist. This results in an invalid state file for B, which cannot be destroyed.

## Solution Suggestion

terraspace all should stop on any error in any stack at each level.

**Comment by johnlister** [comment]
Looks like there is an exit_on_fail config param - surprised this defaults to false

**Comment by tongueroo** [comment]
Thanks for the report. Kind of remember this, at some point was testing `terraspace all down` in rapid-fire fashion and felt like `config.all.exit_on_fail.down = false` was a better deafult. Forgot to update the docs though. Updated it so it reflects the default in the source code https://github.com/boltops-tools/terraspace/blob/0a5a212e033af5d79c47b92b61e422a48e8012fa/lib/terraspace/app.rb#L19

It's useful when was trying to destroy and clean up things over and over and something would fail.

Got some mixed feelings about whether the default for `config.all.exit_on_fail.down` should be true or false. If there are dependency stacks: `A -> B -> C`. And it's destroyed in `C -> B -> A` order. If it fails halfway at B, then running `terraspace all down` again it'll never reach B, since C was already been successfully deleted the first attempt. C will keep failing and exiting. This is why adjusted the default to false. 

At the time, did not run into an issue with the an invalid state file 😔 Right now leaning to leaning leaving the default of `config.all.exit_on_fail.down = false` still. If you want it to be true:

config/app.rb

```ruby
Terraspace.configure do |config|
  config.all.exit_on_fail.down = true
end
```
